%gen_inp

%ename Desamy
%cname 生菜DE
%encoding UTF-8
%selkey 1234567890
%keyname begin
a a
b b
c c
d d
e e
f f
g g
h h
i i
j j
k k
l l
m m
n n
o o
p p
q q
r r
s s
t t
u u
v v
w w
x x
y z
z y
1 1
2 2
3 3
4 4
5 5
6 6
%keyname end
%chardef begin
der Bruder
die Schwester
der Vater
die Mutter
Nacht
Morgen
Nachmittag
Tag
Tschüss    再見
Danke
Null    zero
Eins    one
Zwei    two
Drei    three
Vier    four
Fünf    five
Sechs   six
Sieben  seven
Acht    eight
Neun    nine
Zehn    ten
%chardef end
